Fixed `UnboundLocalError` during migration of a repo with a custom name.
